"""Initial migration

Revision ID: c1f67e2c5f95
Revises: 
Create Date: 2025-11-15 15:59:59.168488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f67e2c5f95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=False),
    sa.Column('oauth_provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('oauth_email', sa.String(length=255), nullable=False),
    sa.Column('oauth_access_token', sa.Text(), nullable=True),
    sa.Column('oauth_refresh_token', sa.Text(), nullable=True),
    sa.Column('oauth_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oauth_id_token', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=512), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_collection_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_collection_interval', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('oauth_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_oauth_email'), 'users', ['oauth_email'], unique=False)
    op.create_index(op.f('ix_users_oauth_provider'), 'users', ['oauth_provider'], unique=False)
    op.create_index(op.f('ix_users_oauth_provider_user_id'), 'users', ['oauth_provider_user_id'], unique=False)
    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.Enum('GMAIL', 'NAVER', 'OUTLOOK', name='emailprovidertype'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetch_error', sa.Text(), nullable=True),
    sa.Column('fetch_interval', sa.Integer(), nullable=False),
    sa.Column('fetch_limit', sa.Integer(), nullable=False),
    sa.Column('folders_to_fetch', sa.JSON(), nullable=False),
    sa.Column('skip_folders', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_email_address'), 'email_accounts', ['email_address'], unique=False)
    op.create_index(op.f('ix_email_accounts_id'), 'email_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_email_accounts_provider_type'), 'email_accounts', ['provider_type'], unique=False)
    op.create_index(op.f('ix_email_accounts_user_id'), 'email_accounts', ['user_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_account_id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=512), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('cc', sa.JSON(), nullable=True),
    sa.Column('bcc', sa.JSON(), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('preview', sa.String(length=500), nullable=True),
    sa.Column('email_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('folder', sa.String(length=100), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('raw_mime_storage_path', sa.String(length=512), nullable=True),
    sa.Column('raw_mime_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='emailstatus'), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('importance_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='importancelevel'), nullable=True),
    sa.Column('classification', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('vector_db_id', sa.String(length=255), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('rule_applied', sa.String(length=100), nullable=True),
    sa.Column('auto_action', sa.String(length=50), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_account_status', 'emails', ['email_account_id', 'status'], unique=False)
    op.create_index('idx_email_account_unprocessed', 'emails', ['email_account_id', 'is_processed'], unique=False)
    op.create_index('idx_email_date_status', 'emails', ['email_date', 'status'], unique=False)
    op.create_index('idx_provider_message', 'emails', ['email_account_id', 'provider_message_id'], unique=True)
    op.create_index(op.f('ix_emails_email_account_id'), 'emails', ['email_account_id'], unique=False)
    op.create_index(op.f('ix_emails_email_date'), 'emails', ['email_date'], unique=False)
    op.create_index(op.f('ix_emails_folder'), 'emails', ['folder'], unique=False)
    op.create_index(op.f('ix_emails_id'), 'emails', ['id'], unique=False)
    op.create_index(op.f('ix_emails_importance_level'), 'emails', ['importance_level'], unique=False)
    op.create_index(op.f('ix_emails_is_archived'), 'emails', ['is_archived'], unique=False)
    op.create_index(op.f('ix_emails_is_deleted'), 'emails', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emails_is_important'), 'emails', ['is_important'], unique=False)
    op.create_index(op.f('ix_emails_is_processed'), 'emails', ['is_processed'], unique=False)
    op.create_index(op.f('ix_emails_is_read'), 'emails', ['is_read'], unique=False)
    op.create_index(op.f('ix_emails_is_starred'), 'emails', ['is_starred'], unique=False)
    op.create_index(op.f('ix_emails_provider_message_id'), 'emails', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_emails_provider_thread_id'), 'emails', ['provider_thread_id'], unique=False)
    op.create_index(op.f('ix_emails_recipient'), 'emails', ['recipient'], unique=False)
    op.create_index(op.f('ix_emails_sender'), 'emails', ['sender'], unique=False)
    op.create_index(op.f('ix_emails_status'), 'emails', ['status'], unique=False)
    op.create_index(op.f('ix_emails_subject'), 'emails', ['subject'], unique=False)
    op.create_index(op.f('ix_emails_vector_db_id'), 'emails', ['vector_db_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_vector_db_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_subject'), table_name='emails')
    op.drop_index(op.f('ix_emails_status'), table_name='emails')
    op.drop_index(op.f('ix_emails_sender'), table_name='emails')
    op.drop_index(op.f('ix_emails_recipient'), table_name='emails')
    op.drop_index(op.f('ix_emails_provider_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_provider_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_is_starred'), table_name='emails')
    op.drop_index(op.f('ix_emails_is_read'), table_name='emails')
    op.drop_index(op.f('ix_emails_is_processed'), table_name='emails')
    op.drop_index(op.f('ix_emails_is_important'), table_name='emails')
    op.drop_index(op.f('ix_emails_is_deleted'), table_name='emails')
    op.drop_index(op.f('ix_emails_is_archived'), table_name='emails')
    op.drop_index(op.f('ix_emails_importance_level'), table_name='emails')
    op.drop_index(op.f('ix_emails_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_folder'), table_name='emails')
    op.drop_index(op.f('ix_emails_email_date'), table_name='emails')
    op.drop_index(op.f('ix_emails_email_account_id'), table_name='emails')
    op.drop_index('idx_provider_message', table_name='emails')
    op.drop_index('idx_email_date_status', table_name='emails')
    op.drop_index('idx_email_account_unprocessed', table_name='emails')
    op.drop_index('idx_email_account_status', table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_email_accounts_user_id'), table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_provider_type'), table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_id'), table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_email_address'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_index(op.f('ix_users_oauth_provider_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_provider'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

