"""Add user_rules table for user-defined email processing rules

Revision ID: fa6b811c6504
Revises: c1f67e2c5f95
Create Date: 2025-11-16 15:48:26.449548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6b811c6504'
down_revision = 'c1f67e2c5f95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.Enum('SIMILARITY_BASED', 'METADATA_BASED', 'CLASSIFICATION_BASED', name='ruletype'), nullable=False),
    sa.Column('action', sa.Enum('DELETE', 'ARCHIVE', 'TAG', 'MOVE', 'MARK_READ', 'MARK_IMPORTANT', name='ruleaction'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reference_email_id', sa.Integer(), nullable=True),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('sender_filter', sa.String(length=255), nullable=True),
    sa.Column('sender_pattern', sa.String(length=255), nullable=True),
    sa.Column('subject_keywords', sa.JSON(), nullable=True),
    sa.Column('subject_pattern', sa.String(length=255), nullable=True),
    sa.Column('category_filter', sa.String(length=50), nullable=True),
    sa.Column('importance_level_filter', sa.String(length=50), nullable=True),
    sa.Column('folder_filter', sa.String(length=100), nullable=True),
    sa.Column('has_attachments_filter', sa.Boolean(), nullable=True),
    sa.Column('classification_category', sa.String(length=50), nullable=True),
    sa.Column('classification_tags', sa.JSON(), nullable=True),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reference_email_id'], ['emails.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_rules_id'), 'user_rules', ['id'], unique=False)
    op.create_index(op.f('ix_user_rules_is_active'), 'user_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_rules_reference_email_id'), 'user_rules', ['reference_email_id'], unique=False)
    op.create_index(op.f('ix_user_rules_rule_type'), 'user_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_user_rules_user_id'), 'user_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_rules_user_id'), table_name='user_rules')
    op.drop_index(op.f('ix_user_rules_rule_type'), table_name='user_rules')
    op.drop_index(op.f('ix_user_rules_reference_email_id'), table_name='user_rules')
    op.drop_index(op.f('ix_user_rules_is_active'), table_name='user_rules')
    op.drop_index(op.f('ix_user_rules_id'), table_name='user_rules')
    op.drop_table('user_rules')
    # ### end Alembic commands ###

